-- schema.sql
CREATE TABLE IF NOT EXISTS PERSONS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS LOCATIONS (
    reference_id BIGINT NOT NULL,
    latitude DOUBLE NOT NULL,
    longitude DOUBLE NOT NULL,
    FOREIGN KEY (reference_id) REFERENCES PERSONS(id)
); 